services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: personal-notes-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=notes_db
      - JWT_SECRET=superSecretKey
      - JWT_EXPIRES_IN=1d
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: personal-notes-frontend
    ports:
      - "3001:3001"
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://api:3000
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
